            <nav class="main-nav">
                <ul>
                    <li class="dropdown">
                        <a href="#" class="dropbtn">Products ▾</a>
                        <div class="dropdown-content">
                            <a href="product1.html">Cacti</a>
                            <a href="product2.html">Succulents</a>
                            <a href="product3.html">Planting Accessories</a>
                            <a href="service1.html">Services</a>
                        </div>
                    </li>
                    <li><a href="order.html">Order</a></li>
                    <li><a href="login.html">Login</a></li>
                </ul>
            </nav>